name: CI - INPE Alertas

on:
  push:
    branches: ['dev', 'feature/**']
  pull_request:
    branches: ['dev']

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # use 20 (ou troque p/ 18 se seu projeto precisar)
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci || npm install

      - name: Rodar ESLint
        run: npm run lint

      - name: Verificar formatação (Prettier)
        run: npm run format:check

      - name: Rodar testes (Jest)
        run: npm test
